[plugin]
repository = "https://github.com/NukoOoOoOoO/GoodMemoryCN.git"
commit = "5a3902de9cf43fc1951c137e23bfe6065b63ef2c"
owners = [
    "ascclemens",
    "VergilGao",
    "Nukoooo",
]
project_path = "GoodMemory"
changelog = "api8"
version = "1.1.3"
