[plugin]
repository = "https://github.com/una-xiv/umbra.git"
commit = "786df25dfa41350662fa375982c0434d630395a0"
owners = [
    "haroldiedema",
    "alexpado",
    "Bloodsoul",
    "MeowZWR"
]
project_path = "Umbra"
