[plugin]
repository = "https://github.com/una-xiv/umbra.git"
commit = "92cf55ad4fe71246b79274e0ce0f95369991f790"
owners = [
    "haroldiedema",
    "alexpado",
    "Bloodsoul",
    "MeowZWR"
]
project_path = "Umbra"
