[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "af5c23d65f2b67fb21dfe296b71e29646f845dc9"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "API15" 
