[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "fbca8cc4f80237066a2b1e81a5731dc1669e7875"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 使用内存而不是网络包
- 添加一个简单的管理窗口
- 修复更改Dalamud目录后，无法读取储存的名字问题
- 添加一个'修改储存路径'的选项
"""
