[plugin]
repository = "https://github.com/decorwdyun/Accountant.git"
commit = "564f23be6f1fae2ead2908af85dbd5e2e0c28bc8"
owners = [
    "Ottermandias",
    "decorwdyun",
]
project_path = "Accountant"
changelog = """\
### Fixed
- 补充遗漏的苗圃信息计时器
"""
