[plugin]
repository = "https://github.com/Yarukon/Accountant.git"
commit = "421b3a7876ad0bd0505aa1996bd13429fd401006"
owners = [
    "Ottermandias",
    "Yarukon"
]
project_path = "Accountant"
changelog = "Updated for Dalamud staging."
