[plugin]
repository = "https://github.com/decorwdyun/Accountant.git"
commit = "ebfa6741180d3c33bce39fc0f2068fd596855ea5"
owners = [
    "Ottermandias",
    "decorwdyun",
]
project_path = "Accountant"
changelog = """\
### Fixed
- 国服支持 & 部分汉化 & bug修复
"""
