[plugin]
repository = "https://github.com/ottercorp/VisibilityPlugin.git"
owners = [ "SheepGoMeh",]
project_path = "Visibility"
commit = "d9897471bb9e45f1312ebd68288a887ce7cea4f8"
changelog = "- Updated plugin for 7.1"
