[plugin]
repository = "https://github.com/ottercorp/VisibilityPlugin.git"
owners = [ "SheepGoMeh",]
project_path = "Visibility"
commit = "dd380557d84734c205b369f56165a2ce491fa67e"
changelog = "- Updated plugin for 7.2"
