[plugin]
repository = "https://github.com/Infiziert90/ChatTwo.git"
commit = "bee0e2e122509bf62b06cce01a21e1b0802e6046"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
changelog = "移除Mare集成，因为以前就是分离配置，理论上不应该出错，如有问题请删除配置重新安装。"
