[plugin]
repository = "https://github.com/Infiziert90/ChatTwo.git"
commit = "78817adb0a67914d9281c1db4afd11e637d7553f"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
