[plugin]
repository = "https://github.com/Infiziert90/ChatTwo.git"
commit = "db490eeab131d0356bb93b8edc2d1bb649b5dde1"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
