[plugin]
repository = "https://github.com/4679/XIVWindowResizer.git"
commit = "2ac96fccc231bb08b58d872a944e1d365d882977"
owners = ["AlexCSDev", "4679"]
project_path = "XIVWindowResizer"
changelog = "CN 6.3"
