[plugin]
repository = "https://github.com/4679/XIVWindowResizer.git"
commit = "29d90f9c7cfc3b9451b94b30dc5176ecfdd21ffe"
owners = ["AlexCSDev", "4679"]
project_path = "XIVWindowResizer"
changelog = "CN 6.3"
