[plugin]
repository = "https://github.com/4679/XIVWindowResizer.git"
commit = "bce2015a7a0c538ad4812876d502461662ba721c"
owners = ["AlexCSDev", "4679"]
project_path = "XIVWindowResizer"
changelog = "CN 7.2"
