[plugin]
repository = "https://github.com/4679/XIVWindowResizer.git"
commit = "ccb0537d870a0a6c05b87dd045e229506edb7cbe"
owners = ["AlexCSDev", "4679"]
project_path = "XIVWindowResizer"
changelog = "CN 7.3"
