[plugin]
repository = "https://github.com/4679/XIVWindowResizer.git"
commit = "06f7ba0534be907307286750aecde5fd947684f8"
owners = ["AlexCSDev", "4679"]
project_path = "XIVWindowResizer"
changelog = "CN 7.1"
