[plugin]
repository = "https://github.com/lzt9746/mp-tick-bar.git"
commit = "94f0d0721097c78438d304670465bd03e97dfd5d"
owners = ["marconsou","lzt9746"]
project_path = "MPTickBar"
changelog = """Version 1.4.1.5
- 适配国服
"""
