[plugin]
repository = 'https://github.com/MapleRecall/OrangeGuidanceTomestone.git'
commit = '07b1caf2f4467f6ec8141d448e58ef6a3a5f46ed'
owners = [ 'anna-is-cute', 'MapleRecall' ]
project_path = 'client'
changelog = """\
- 适配 7.5（api15）
"""
