[plugin]
repository = 'https://github.com/MapleRecall/OrangeGuidanceTomestone.git'
commit = 'aad332b7f4f9f0cf6069a799f53134cef507995c'
owners = [ 'anna-is-cute', 'MapleRecall' ]
project_path = 'client'
changelog = """\
- 简单汉化一下？
"""
