[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "e9afe23dc0e2acfdabac764df35bd2567559a3d0"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = """
- Fixed a file save failure error that occurred when a specific item name contained characters that could not be used as a file name.
"""
