[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "2add6c317d773fa4cc50fb9eb1a653b5c04a31b7"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 修复了部分输入框长度不足的问题\n- 修复了 自动备份 功能下的一些问题"
