[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "b17638f760b64474977f2acfd22a6e93f6a32598"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 修复了部分输入框长度不足的问题\n- 修复了 自动备份 功能下的一些问题"
