[plugin]
repository = "https://github.com/Ookura-Risona/QoLBar.git"
commit = "629155c861a05a4eed50705c05e98d5352fe13ac"
owners = [
    "UnknownX7",
    "Ookura-Risona" 
]
changelog = '''
- Fixed for 7.3 (Thanks to Ottermandias)
- Known Issue: Some icon colors are currently off'''
