[plugin]
repository = "https://github.com/AtmoOmen/casexile.git"
commit = "15cd09622b48eb208aed363df417bc03bfeb0a81"
owners = ["RyouBakura", "AtmoOmen"]
project_path = ""
changelog = "Initial Release"
