[plugin]
repository = "https://github.com/VeroFess/ffxiv-priceinsight-cn.git"
commit = "e54094a34a78fd14e514cd26da207056a9647d1b"
owners = ["Kouzukii","VeroFess"]
project_path = ""
changelog = """
- 合并上游错误修正
"""