[plugin]
repository = 'https://github.com/NiGuangOwO/BetterPartyFinder.git'
commit = 'ebc10ea58360cc4c8bddc7775fb6644e861400bf'
owners = [ 'lojewalo' , 'NiGuangOwO']
changelog = '特别关心的招募出现时，添加可点击的招募链接'
