[plugin]
repository = "https://github.com/MapleRecall/FFXIVAetherCompass.git"
commit = "021b9d59a7d8882b417d4963ef7c32b80ef4695f"
owners = [ "Cytraen", "MapleRecall" ]
changelog = "Update for 7.3 / API 13"
