[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "7146cec2380adcf0ab79a1ea332082a96dc24770"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 请查阅 GitHub 更新日志页面"
