[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "fb104b2edb7234a76ba9fccd355a059ac4afbe15"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 解决文件进程冲突问题"
