[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "e3932306a8d09f02450ca29b1bf5c852217cb256"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 请查阅更新日志页面"
