[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "3cd72939186794044dfad77fe2cbaee2919f72c0"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 解决文件进程冲突问题"
