[plugin]
repository = "https://github.com/DutyPusher/FFXIVDutyPusher.git"
commit = "b64dc258773481e22b42f5cb8b42ed0ec9ee12f9"
owners = ["MorCherlf"]
project_path = "DutyPusher"
changelog = """\
Update API 15 For CN
"""