[plugin]
repository = "https://github.com/decorwdyun/InventoryTools.git"
commit = "2746fac87b4b45fb4c47a1e12d3ef6b21a93e959"
owners = [
    "Critical-Impact",
    "decorwdyun"
]
project_path = "InventoryTools"
version = "1.7.0.23"
changelog = """\
### Fixed
- 国服 hotfix，修复了最近出现的报错问题

"""
