[plugin]
repository = "https://github.com/decorwdyun/InventoryTools.git"
commit = "6eb5380a5f953f07a615a4adedc5414f11ba2766"
owners = [
    "Critical-Impact",
    "decorwdyun"
]
project_path = "InventoryTools"
version = "1.11.1.4"
