[plugin]
repository = "https://github.com/wozaiha/ARealmRecorded.git"
commit = "b260e582e9090b8d5771af0edf3e445bafe4e156"
owners = [ "UnknownX7" ]
changelog = '''
- Added support for Chaotic raids (Aireil tested and approved)'''
