[plugin]
repository = "https://github.com/AtmoOmen/Hunty.git"
commit = "5d179e9101ccc47039633b8a0440244d9798585d"
owners = [
    "Infiziert90",
    "AtmoOmen"
]
project_path = "Hunty"
changelog = """
nofranz
"""
