[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "b940a5960fc50d4c3e1ef178dab2f979b1c879be"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 使用内存而不是网络包
- 添加一个简单的管理窗口
"""
