[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "7f74bbd9b7e31d4071816163965e6bc0c97955e0"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 使用内存而不是网络包
- 添加一个简单的管理窗口
"""
