[plugin]
repository = "https://github.com/AtmoOmen/EurekaHelper.git"
commit = "53ce4dcc13d9efd04f49b85950818dfb4c2a96fb"
owners = ["snorux", "AtmoOmen"]
project_path = "EurekaHelper"
changelog = """
Elemental Manager
- Added crowdsourced positions

Misc
- Updated to API 9
"""
