[plugin]
repository = "https://github.com/snorux/EurekaHelper.git"
commit = "4f101c21cb00b0e32f98915ba1cc2b547392e877"
owners = ["snorux"]
project_path = "EurekaHelper"
changelog = """
Elemental Manager
- Added crowdsourced positions

Misc
- Updated to API 9
"""
