[plugin]
repository = "https://github.com/KirisameVanilla/HuntHelper.git"
commit = "d9b8b5b858af69cf88bf761c9add253975fe2d64"
owners = [
    "img02",
    "KirisameVanilla",
]
project_path = "HuntHelper"