[plugin]
repository = "https://github.com/ottercorp/Distance.git"
commit = "da73426af71052af6ee0d7ac70849b3b6dfcd08c"
owners = [
    "PunishedPineapple",
    "MapleRecall"
]
project_path = "Distance"
changelog = '''
'''
