[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = 'd2211cea772d5514633912697481da7fea7e7e84'
owners = [ 'lojewalo' , 'LittleNightmare']
project_path = 'csharp/RemotePartyFinder'
changelog = '无内容更新，修复不存在'
