[plugin]
repository = "https://github.com/ddez180001/LogogramHelper.git"
commit = "bea16d00e45921028e14e97c6a383830fa1603a5"
owners = ["apetih", "ddez180001"]
project_path = "LogogramHelper"
changelog = """
汉化
"""
