[plugin]
repository = "https://github.com/AtmoOmen/DeepDungeonDex.git"
owners = [ "wolfcomp", "AtmoOmen" ]
project_path = "DeepDungeonDex"
commit = "5aab3ebba33129cacae01f05238e77982e576d84"
changelog = "### 2.7.1 (2023-09-04)\n\n\n### Bug Fixes\n\n* dont open debug window on init (50b123a)"
version = "2.7.1"
