[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = '6a20cbd96ed4589d59ee7077d346dc58cac59070'
owners = [ 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'Update for api v15'
