[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = 'd1464f949df09d9be5fbb6420aca51750b0401e8'
owners = [ 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'Update for api v15'
