[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "3bebf870ec35c6de2d6a3bf6c660cea5fdbc3bce"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """
- CN 7.5
"""
