[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "8f3c588be50cc5ebdd2c4b7919fbe01f2ff3019e"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """
- CN 7.5
"""
