[plugin]
repository = "https://github.com/zhouhuichen741/ffxiv-characterstatus-refined.git"
commit = "d52fd50276c73b456bed360ed274a8abf3b8d037"
owners = ["Kouzukii", "zhouhuichen741"]
project_path = "CharacterPanelRefined"
changelog = """
- Update to FFXIV 7.5 and Dalamud 15
- Add CN
"""
