[plugin]
repository = "https://github.com/shdwp/xivPartyIcons.git"
commit = "f50d9e590c331deca5790e15d97da71d6e32df51"
owners = [
    "shdwp",
    "avafloww",
    "squidmade",
]
project_path = "PartyIcons"
changelog = """
- In the settings window, Testing Mode and the General tab now flash when enabled 
- Fixed a bug when converting v1 to v2 config where Game Default chat settings resulted in role colors being enabled
- Refactored UI code
"""