[plugin]
repository = "https://github.com/cyf2023/WaymarkPresetPlugin.git"
commit = "968f01f24f1b5c7af7bf277cc39dfa69bafbda89"
owners = [
    "PunishedPineapple",
    "abashby",
    "Infiziert90",
    "cyf2023"
]
project_path = "WaymarkPresetPlugin"
changelog = '''
汉化。
'''
