[plugin]
repository = "https://github.com/LittleNightmare/PrefPro.git"
commit = "341c93fc7867cde80af78e9ca44b5f502ed44904"
owners = [
    "lmcintyre",
    "LittleNightmare",
]
project_path = "PrefPro"
